"""empty message

Revision ID: 171ac3d417f6
Revises: 
Create Date: 2024-11-05 18:36:21.684000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '171ac3d417f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ap_comments',
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('comment', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Date')
    )
    op.create_table('ap_preds',
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('predicted', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('Date')
    )
    op.create_table('gg_preds',
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('predicted', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('Date')
    )
    op.create_table('nf_comments',
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('comment', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Date')
    )
    op.drop_table('gg_preds')
    op.drop_table('ap_preds')
    op.drop_table('ap_comment')
    op.drop_table('nf_comments')
    op.drop_table('ap_comments')
    with op.batch_alter_table('gg_comments', schema=None) as batch_op:
        batch_op.alter_column('Date',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('gold_comments', schema=None) as batch_op:
        batch_op.alter_column('Date',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('gold_preds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Date', sa.Date(), nullable=False))
        batch_op.alter_column('predicted',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               nullable=False)
        batch_op.drop_column('date')

    with op.batch_alter_table('nf_preds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Date', sa.Date(), nullable=False))
        batch_op.alter_column('predicted',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               nullable=False)
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nf_preds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('predicted',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=True)
        batch_op.drop_column('Date')

    with op.batch_alter_table('gold_preds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('predicted',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=True)
        batch_op.drop_column('Date')

    with op.batch_alter_table('gold_comments', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('Date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('gg_comments', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('Date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=50),
               nullable=True)

    op.create_table('ap_comments',
    sa.Column('Date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=50), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('nf_comments',
    sa.Column('Date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=50), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ap_comment',
    sa.Column('Date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('comments', mysql.VARCHAR(length=50), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ap_preds',
    sa.Column('date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('predicted', mysql.DOUBLE(asdecimal=True), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('gg_preds',
    sa.Column('date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('predicted', mysql.DOUBLE(asdecimal=True), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('nf_Comments')
    op.drop_table('gg_Preds')
    op.drop_table('ap_reds')
    op.drop_table('ap_Comments')
    # ### end Alembic commands ###
