# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_View.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(483, 378)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 30, 291, 181))
        self.frame.setAcceptDrops(False)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Log_list = QtWidgets.QListView(Dialog)
        self.Log_list.setGeometry(QtCore.QRect(310, 51, 131, 171))
        self.Log_list.setObjectName("Log_list")
        self.verticalScrollBar = QtWidgets.QScrollBar(Dialog)
        self.verticalScrollBar.setGeometry(QtCore.QRect(440, 50, 20, 171))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.video_down_button = QtWidgets.QPushButton(Dialog)
        self.video_down_button.setGeometry(QtCore.QRect(380, 230, 61, 23))
        self.video_down_button.setObjectName("video_down_button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(310, 30, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_2.setObjectName("label_2")
        self.video_after_button_2 = QtWidgets.QPushButton(Dialog)
        self.video_after_button_2.setGeometry(QtCore.QRect(20, 310, 101, 41))
        self.video_after_button_2.setObjectName("video_after_button_2")
        self.video_before_button_2 = QtWidgets.QPushButton(Dialog)
        self.video_before_button_2.setGeometry(QtCore.QRect(40, 5, 31, 21))
        self.video_before_button_2.setMaximumSize(QtCore.QSize(51, 16777215))
        self.video_before_button_2.setObjectName("video_before_button_2")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(90, 260, 167, 41))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.video_before_button = QtWidgets.QPushButton(self.groupBox)
        self.video_before_button.setMaximumSize(QtCore.QSize(51, 16777215))
        self.video_before_button.setObjectName("video_before_button")
        self.horizontalLayout.addWidget(self.video_before_button)
        self.video_stop_button = QtWidgets.QPushButton(self.groupBox)
        self.video_stop_button.setMaximumSize(QtCore.QSize(51, 16777215))
        self.video_stop_button.setObjectName("video_stop_button")
        self.horizontalLayout.addWidget(self.video_stop_button)
        self.video_after_button = QtWidgets.QPushButton(self.groupBox)
        self.video_after_button.setMaximumSize(QtCore.QSize(51, 16777215))
        self.video_after_button.setObjectName("video_after_button")
        self.horizontalLayout.addWidget(self.video_after_button)
        self.groupBox1 = QtWidgets.QGroupBox(Dialog)
        self.groupBox1.setGeometry(QtCore.QRect(21, 231, 281, 31))
        self.groupBox1.setObjectName("groupBox1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_2.addWidget(self.horizontalSlider)
        self.label_5 = QtWidgets.QLabel(self.groupBox1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.setting_button = QtWidgets.QPushButton(Dialog)
        self.setting_button.setGeometry(QtCore.QRect(130, 310, 101, 41))
        self.setting_button.setObjectName("setting_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MainView"))
        self.video_down_button.setText(_translate("Dialog", "영상 저장"))
        self.label.setText(_translate("Dialog", "로그"))
        self.label_2.setText(_translate("Dialog", "영상"))
        self.video_after_button_2.setText(_translate("Dialog", "랙 영역"))
        self.video_before_button_2.setText(_translate("Dialog", "📂"))
        self.video_before_button.setText(_translate("Dialog", "◁"))
        self.video_stop_button.setText(_translate("Dialog", "❚❚"))
        self.video_after_button.setText(_translate("Dialog", "▷"))
        self.label_3.setText(_translate("Dialog", "11:00"))
        self.label_5.setText(_translate("Dialog", "13:00"))
        self.setting_button.setText(_translate("Dialog", "설정"))

class Main(QtWidgets.QMainWindow, Ui_Dialog): # Ui_MainWindow
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setting_page = None
        self.setting_button.clicked.connect(self.go_setting)

    def go_setting(self):
        print("세팅창 열어줘")
        if self.setting_page is None:
            self.setting_page = setting_page()  # SettingWindow 인스턴스화
        self.setting_page.show()
        print("세팅창 열기")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
