# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setting(QtWidgets.QWidget):
    def setupUi(self, setting):
        setting.setObjectName("setting")
        setting.setWindowModality(QtCore.Qt.ApplicationModal)
        setting.resize(400, 300)
        self.checkBox = QtWidgets.QCheckBox(setting)
        self.checkBox.setGeometry(QtCore.QRect(20, 40, 221, 16))
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(setting)
        self.label.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label.setMinimumSize(QtCore.QSize(54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(setting)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 121, 21))
        self.label_2.setObjectName("label_2")
        self.checkBox_2 = QtWidgets.QCheckBox(setting)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 60, 291, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(setting)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 80, 271, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_3 = QtWidgets.QLabel(setting)
        self.label_3.setGeometry(QtCore.QRect(80, 160, 101, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(setting)
        self.comboBox.setGeometry(QtCore.QRect(10, 160, 67, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(setting)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 121, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(setting)
        self.label_5.setGeometry(QtCore.QRect(60, 210, 41, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(setting)
        self.label_6.setGeometry(QtCore.QRect(100, 210, 151, 21))
        self.label_6.setObjectName("label_6")
        self.video_before_button_2 = QtWidgets.QPushButton(setting)
        self.video_before_button_2.setGeometry(QtCore.QRect(20, 210, 31, 21))
        self.video_before_button_2.setMaximumSize(QtCore.QSize(51, 16777215))
        self.video_before_button_2.setObjectName("video_before_button_2")

        self.retranslateUi(setting)
        QtCore.QMetaObject.connectSlotsByName(setting)

    def retranslateUi(self, setting):
        _translate = QtCore.QCoreApplication.translate
        setting.setWindowTitle(_translate("setting", "setting"))
        self.checkBox.setText(_translate("setting", "1. 위험구역 진입"))
        self.label.setText(_translate("setting", "알림 설정"))
        self.label_2.setText(_translate("setting", "UI 텍스트 굵기 설정"))
        self.checkBox_2.setText(_translate("setting", "2. 사람 - 지게차 간 충돌 거리 진입"))
        self.checkBox_3.setText(_translate("setting", "3. "))
        self.label_3.setText(_translate("setting", "미리보기 텍스트"))
        self.comboBox.setItemText(0, _translate("setting", "10px"))
        self.comboBox.setItemText(1, _translate("setting", "15px"))
        self.comboBox.setItemText(2, _translate("setting", "20px"))
        self.label_4.setText(_translate("setting", "파일 저장 위치 변경"))
        self.label_5.setText(_translate("setting", "현재 :"))
        self.label_6.setText(_translate("setting", "C:KDTvideo"))
        self.video_before_button_2.setText(_translate("setting", "📂"))


# class setting_page(QtWidgets.QMainWindow):
#     def __init__(self):
#         super().__init__()
#         self.setWindowTitle("Settings")
#         self.setGeometry(200, 200, 400, 300) 

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     setting = QtWidgets.QDialog()
#     ui = Ui_setting()
#     ui.setupUi(setting)
#     setting.show()
#     sys.exit(app.exec_())
